services:
  rampa-cash-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # Add your environment variables here
      # - SOLANA_PRIVATE_KEY=your_private_key_here
      # - TWILIO_ACCOUNT_SID=your_twilio_sid
      # - TWILIO_AUTH_TOKEN=your_twilio_token
      # - TWILIO_PHONE_NUMBER=your_twilio_phone
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/waitlist"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service (optional)
  rampa-cash-web-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    profiles:
      - dev 